apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: default
  labels:
    kubernetes.io/metadata.name: default
  annotations:
    openshift.io/display-name: ''
    openshift.io/description: ''
    openshift.io/requester: kubeadmin
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
